apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlsystem-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: px-mssql-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqldata-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: px-mssql-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqllog-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: px-mssql-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi